# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/Request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Requests import RequestType_pb2 as Requests_dot_RequestType__pb2

from Requests.RequestType_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/Request.proto',
  package='POGOProtos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n\x16Requests/Request.proto\x12\x13POGOProtos.Requests\x1a\x1aRequests/RequestType.proto\"Z\n\x07Request\x12\x36\n\x0crequest_type\x18\x01 \x01(\x0e\x32 .POGOProtos.Requests.RequestType\x12\x17\n\x0frequest_message\x18\x02 \x01(\x0cP\x00\x62\x06proto3')
  ,
  dependencies=[Requests_dot_RequestType__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='POGOProtos.Requests.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='POGOProtos.Requests.Request.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_message', full_name='POGOProtos.Requests.Request.request_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=165,
)

_REQUEST.fields_by_name['request_type'].enum_type = Requests_dot_RequestType__pb2._REQUESTTYPE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'Requests.Request_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Requests.Request)
  ))
_sym_db.RegisterMessage(Request)


# @@protoc_insertion_point(module_scope)
