# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/Messages/GetDownloadSettingsMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/Messages/GetDownloadSettingsMessage.proto',
  package='POGOProtos.Requests.Messages',
  syntax='proto3',
  serialized_pb=_b('\n2Requests/Messages/GetDownloadSettingsMessage.proto\x12\x1cPOGOProtos.Requests.Messages\"*\n\x1aGetDownloadSettingsMessage\x12\x0c\n\x04hash\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETDOWNLOADSETTINGSMESSAGE = _descriptor.Descriptor(
  name='GetDownloadSettingsMessage',
  full_name='POGOProtos.Requests.Messages.GetDownloadSettingsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='POGOProtos.Requests.Messages.GetDownloadSettingsMessage.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['GetDownloadSettingsMessage'] = _GETDOWNLOADSETTINGSMESSAGE

GetDownloadSettingsMessage = _reflection.GeneratedProtocolMessageType('GetDownloadSettingsMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETDOWNLOADSETTINGSMESSAGE,
  __module__ = 'Requests.Messages.GetDownloadSettingsMessage_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Requests.Messages.GetDownloadSettingsMessage)
  ))
_sym_db.RegisterMessage(GetDownloadSettingsMessage)


# @@protoc_insertion_point(module_scope)
